<?php
namespace common\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * Class XmlFiles
 * @package common\models
 *
 * @property integer $id
 * @property string $name
 * @property integer $created_at
 *
 * @property XmlFilesTags $tags Related tags
 */
class XmlFiles extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%xml_files%}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @return array
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this
            ->hasMany(XmlFilesTags::class, ['file_id' => 'id'])
            ->orderBy(['tag' => SORT_ASC]);
    }
}